{
 "title": "dashboard test",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Requests fallidas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(http_5xx_responses_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "user/login",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{handler=\"/user/login\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Comprar productos",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{handler=\"/user/buy\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Añadir a favoritos",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{handler=\"/user/addFavorite\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Comprados por el usuario",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{handler=\"/user/shopped\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "process_start_time_seconds", "legendFormat": "__auto" },
    { "expr": "process_cpu_seconds_total", "legendFormat": "__auto" }
   ]
  }
 ]
}